spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/VuLanTuong/cloud-config-server
          clone-on-start: true
        bootstrap: true
      enabled: true

  application:
    name: config-server